/// Application commands that get `allow-*`/`deny-*` permissions generated in
/// `permissions/autogenerated`; once declared, each needs an explicit capability.
const APP_COMMANDS: &[&str] = &[
    "project_create",
    "project_open",
    "project_close",
    "report_save_xlsx",
];

fn main() {
    let windows_msvc = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows")
        && std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc");
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    if windows_msvc {
        // tauri-build embeds its resource manifest only in bin targets. Rust test
        // executables also link TaskDialogIndirect and need Common Controls v6.
        // Use the upstream Tauri example's linker approach for all executable targets:
        // https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/build.rs
        tauri_build::try_build(
            attributes
                .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest()),
        )
        .expect("failed to prepare Tauri resources");
        let manifest = std::path::PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap())
            .join("windows-app-manifest.xml");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
    } else {
        tauri_build::try_build(attributes).expect("failed to prepare Tauri resources");
    }
}
